[package]
name = "cdp-distort"
version = "0.1.0"
edition = "2021"

[dependencies]
cdp-core = { path = "../cdp-core" }
hound = "3.5"
thiserror = "1.0"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
approx = "0.5"