# CDP-RS Rust Formatting Configuration
# Using only stable features

edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
max_width = 100
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true