name: CDP Oracle Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-frozen-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Check frozen modules unchanged
      run: |
        # List of frozen modules
        FROZEN_MODULES="cdp-core cdp-pvoc cdp-spectral"
        
        # Check if any frozen module was modified
        for module in $FROZEN_MODULES; do
          if git diff --name-only origin/main HEAD | grep -q "^$module/"; then
            echo "ERROR: Frozen module $module was modified!"
            echo "Frozen modules can only be changed with explicit approval."
            exit 1
          fi
        done
        
        echo "✓ All frozen modules unchanged"

  oracle-tests:
    runs-on: ubuntu-latest
    needs: check-frozen-modules
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install CDP binaries
      run: |
        # Download CDP binaries (would need actual CDP release URL)
        # wget https://github.com/ComposersDesktop/CDP8/releases/...
        # tar -xzf cdp-binaries.tar.gz
        # export PATH=$PATH:$PWD/cdp/bin
        echo "CDP binary installation would go here"
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run oracle validation tests
      run: |
        cargo test --package cdp-oracle --features integration-tests
    
    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-outputs
        path: |
          target/oracle-tests/
          **/*.wav

  performance:
    runs-on: ubuntu-latest
    needs: oracle-tests
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Run benchmarks
      run: |
        cargo bench --all
    
    - name: Compare with baseline
      run: |
        # Would compare with stored baseline performance
        echo "Performance comparison would go here"