name: CDP Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  validate:
    name: Full Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git python3
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache CDP build
      uses: actions/cache@v4
      with:
        path: |
          build/cdp
          build/cdp-install
        key: ${{ runner.os }}-cdp-${{ hashFiles('scripts/build-cdp.sh') }}
        restore-keys: |
          ${{ runner.os }}-cdp-
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run full validation (exactly like local)
      run: |
        make clean
        make install-cdp
        make
    
    - name: Upload artifacts on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-outputs
        path: |
          target/debug/deps/
          **/*.wav
          **/*.ana